// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;

namespace ElectroAPI.Models;

public partial class Category
{
    public int CategoryId { get; set; }

    public string Name { get; set; } = null!;

    public string? Description { get; set; }

    public int? MainCategory { get; set; }

    public virtual ICollection<Category> InverseMainCategoryNavigation { get; set; } = new List<Category>();

    public virtual Category? MainCategoryNavigation { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}
