// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;

namespace ElectroAPI.Models;

public partial class Payment
{
    public int PaymentId { get; set; }

    public DateOnly? PaymentDate { get; set; }

    public string? Amount { get; set; }

    public string? Status { get; set; }

    public string? Method { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}
