// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;

namespace ElectroAPI.Models;

public partial class Review
{
    public int ReviewId { get; set; }

    public DateOnly? Date { get; set; }

    public string? Comment { get; set; }

    public int? Rating { get; set; }

    public int? CustomerId { get; set; }

    public int? ProductId { get; set; }

    public virtual Customer? Customer { get; set; }

    public virtual Product? Product { get; set; }
}
