// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;

namespace ElectroAPI.Models;

public partial class Shipment
{
    public int ShipmentId { get; set; }

    public DateOnly? DeliveryDate { get; set; }

    public DateOnly? ShipmentDate { get; set; }

    public string? Amount { get; set; }

    public string? Status { get; set; }

    public string? CurrierName { get; set; }

    public int? TrackingNumber { get; set; }

    public int? OrderId { get; set; }

    public virtual Order? Order { get; set; }
}
