// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;

namespace ElectroAPI.Models;

public partial class StockTransaction
{
    public int TranId { get; set; }

    public DateOnly? TranDate { get; set; }

    public string? Type { get; set; }

    public int? QuantityChange { get; set; }

    public string? Reference { get; set; }

    public int? ProductId { get; set; }

    public virtual Product? Product { get; set; }
}
