// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;

namespace ElectroAPI.Models;

public partial class Supplier
{
    public int SupplierId { get; set; }

    public string Name { get; set; } = null!;

    public string? Country { get; set; }

    public string Email { get; set; } = null!;

    public string? Address { get; set; }

    public int? ContactNumber { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}
